apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-[stage]
spec:
  replicas: [replicas]
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: helloworld
        stage: [stage]
    spec:
      containers:
      - name: helloworld
        image: quay.io/aleks_saul/hello_world:[tag]
        env:
        - name: HELLOWORLD_DISPLAYEXTERNALIP
          value: "false"
        - name: HELLOWORLD_DISPLAYGEOLOCATION
          value: "false"
        - name: HELLOWORLD_CRASHAPP
          value: "false"
        - name: HELLOWORLD_CRASHAPPCOUNT
          value: "5" 
        - name: HELLOWORLD_DEBUG
          value: "true"
        - name: HELLOWORLD_SIMULATEREADY
          value: "false"
        - name: HELLOWORLD_WAITBEFOREREADY
          value: "30" 
        resources:
          requests:
            cpu: "200m"
            memory: "64Mi"
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          
